version: '3.8'

services:
  cutm-courseware-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cutm-courseware-platform
    ports:
      - "8080:80"
    restart: always
    environment:
      - NODE_ENV=production
